/**
 * Generates packages/core/src/generated/types.ts from the OpenAPI spec
 * via the openapi-typescript JS API.
 *
 * Run: npm run gen (repo root) or tsx src/gen-types.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const SPEC_URL = new URL("../../../specs/kit-swagger.openapi.json", import.meta.url);
const OUT_DIR = fileURLToPath(new URL("../../core/src/generated/", import.meta.url));

const HEADER = "// GENERATED by yandex-kit-codegen — do not edit, run: npm run gen\n";

const ast = await openapiTS(SPEC_URL);
const contents = HEADER + astToString(ast);

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_DIR + "types.ts", contents);

console.log(`gen-types: wrote types.ts (${contents.length} chars)`);
